package gb

// Instruction describes a single decoded opcode.
type Instruction struct {
	Mnemonic     string
	Cycles       int
	OperandBytes int
}

// Decode looks up a main opcode (0x00-0xFF) in the instruction table.
func Decode(op byte) Instruction {
	return mainTable[op]
}

// DecodeCB looks up a CB-prefixed opcode (0x00-0xFF) in the CB instruction table.
func DecodeCB(op byte) Instruction {
	return cbTable[op]
}

// mainTable maps every 0x00-0xFF opcode to its instruction metadata.
var mainTable = [256]Instruction{
	// 0x00-0x0F
	0x00: {Mnemonic: "NOP", Cycles: 4, OperandBytes: 0},
	0x01: {Mnemonic: "LD BC,d16", Cycles: 12, OperandBytes: 2},
	0x02: {Mnemonic: "LD (BC),A", Cycles: 8, OperandBytes: 0},
	0x03: {Mnemonic: "INC BC", Cycles: 8, OperandBytes: 0},
	0x04: {Mnemonic: "INC B", Cycles: 4, OperandBytes: 0},
	0x05: {Mnemonic: "DEC B", Cycles: 4, OperandBytes: 0},
	0x06: {Mnemonic: "LD B,d8", Cycles: 8, OperandBytes: 1},
	0x07: {Mnemonic: "RLCA", Cycles: 4, OperandBytes: 0},
	0x08: {Mnemonic: "LD (a16),SP", Cycles: 20, OperandBytes: 2},
	0x09: {Mnemonic: "ADD HL,BC", Cycles: 8, OperandBytes: 0},
	0x0A: {Mnemonic: "LD A,(BC)", Cycles: 8, OperandBytes: 0},
	0x0B: {Mnemonic: "DEC BC", Cycles: 8, OperandBytes: 0},
	0x0C: {Mnemonic: "INC C", Cycles: 4, OperandBytes: 0},
	0x0D: {Mnemonic: "DEC C", Cycles: 4, OperandBytes: 0},
	0x0E: {Mnemonic: "LD C,d8", Cycles: 8, OperandBytes: 1},
	0x0F: {Mnemonic: "RRCA", Cycles: 4, OperandBytes: 0},
	// 0x10-0x1F
	0x10: {Mnemonic: "STOP", Cycles: 4, OperandBytes: 0},
	0x11: {Mnemonic: "LD DE,d16", Cycles: 12, OperandBytes: 2},
	0x12: {Mnemonic: "LD (DE),A", Cycles: 8, OperandBytes: 0},
	0x13: {Mnemonic: "INC DE", Cycles: 8, OperandBytes: 0},
	0x14: {Mnemonic: "INC D", Cycles: 4, OperandBytes: 0},
	0x15: {Mnemonic: "DEC D", Cycles: 4, OperandBytes: 0},
	0x16: {Mnemonic: "LD D,d8", Cycles: 8, OperandBytes: 1},
	0x17: {Mnemonic: "RLA", Cycles: 4, OperandBytes: 0},
	0x18: {Mnemonic: "JR r8", Cycles: 12, OperandBytes: 1},
	0x19: {Mnemonic: "ADD HL,DE", Cycles: 8, OperandBytes: 0},
	0x1A: {Mnemonic: "LD A,(DE)", Cycles: 8, OperandBytes: 0},
	0x1B: {Mnemonic: "DEC DE", Cycles: 8, OperandBytes: 0},
	0x1C: {Mnemonic: "INC E", Cycles: 4, OperandBytes: 0},
	0x1D: {Mnemonic: "DEC E", Cycles: 4, OperandBytes: 0},
	0x1E: {Mnemonic: "LD E,d8", Cycles: 8, OperandBytes: 1},
	0x1F: {Mnemonic: "RRA", Cycles: 4, OperandBytes: 0},
	// 0x20-0x2F
	0x20: {Mnemonic: "JR NZ,r8", Cycles: 12, OperandBytes: 1},
	0x21: {Mnemonic: "LD HL,d16", Cycles: 12, OperandBytes: 2},
	0x22: {Mnemonic: "LDI (HL),A", Cycles: 8, OperandBytes: 0},
	0x23: {Mnemonic: "INC HL", Cycles: 8, OperandBytes: 0},
	0x24: {Mnemonic: "INC H", Cycles: 4, OperandBytes: 0},
	0x25: {Mnemonic: "DEC H", Cycles: 4, OperandBytes: 0},
	0x26: {Mnemonic: "LD H,d8", Cycles: 8, OperandBytes: 1},
	0x27: {Mnemonic: "DAA", Cycles: 4, OperandBytes: 0},
	0x28: {Mnemonic: "JR Z,r8", Cycles: 12, OperandBytes: 1},
	0x29: {Mnemonic: "ADD HL,HL", Cycles: 8, OperandBytes: 0},
	0x2A: {Mnemonic: "LDI A,(HL)", Cycles: 8, OperandBytes: 0},
	0x2B: {Mnemonic: "DEC HL", Cycles: 8, OperandBytes: 0},
	0x2C: {Mnemonic: "INC L", Cycles: 4, OperandBytes: 0},
	0x2D: {Mnemonic: "DEC L", Cycles: 4, OperandBytes: 0},
	0x2E: {Mnemonic: "LD L,d8", Cycles: 8, OperandBytes: 1},
	0x2F: {Mnemonic: "CPL", Cycles: 4, OperandBytes: 0},
	// 0x30-0x3F
	0x30: {Mnemonic: "JR NC,r8", Cycles: 12, OperandBytes: 1},
	0x31: {Mnemonic: "LD SP,d16", Cycles: 12, OperandBytes: 2},
	0x32: {Mnemonic: "LDD (HL),A", Cycles: 8, OperandBytes: 0},
	0x33: {Mnemonic: "INC SP", Cycles: 8, OperandBytes: 0},
	0x34: {Mnemonic: "INC (HL)", Cycles: 12, OperandBytes: 0},
	0x35: {Mnemonic: "DEC (HL)", Cycles: 12, OperandBytes: 0},
	0x36: {Mnemonic: "LD (HL),d8", Cycles: 12, OperandBytes: 1},
	0x37: {Mnemonic: "SCF", Cycles: 4, OperandBytes: 0},
	0x38: {Mnemonic: "JR C,r8", Cycles: 12, OperandBytes: 1},
	0x39: {Mnemonic: "ADD HL,SP", Cycles: 8, OperandBytes: 0},
	0x3A: {Mnemonic: "LDD A,(HL)", Cycles: 8, OperandBytes: 0},
	0x3B: {Mnemonic: "DEC SP", Cycles: 8, OperandBytes: 0},
	0x3C: {Mnemonic: "INC A", Cycles: 4, OperandBytes: 0},
	0x3D: {Mnemonic: "DEC A", Cycles: 4, OperandBytes: 0},
	0x3E: {Mnemonic: "LD A,d8", Cycles: 8, OperandBytes: 1},
	0x3F: {Mnemonic: "CCF", Cycles: 4, OperandBytes: 0},
	// 0x40-0x4F
	0x40: {Mnemonic: "LD B,B", Cycles: 4, OperandBytes: 0},
	0x41: {Mnemonic: "LD B,C", Cycles: 4, OperandBytes: 0},
	0x42: {Mnemonic: "LD B,D", Cycles: 4, OperandBytes: 0},
	0x43: {Mnemonic: "LD B,E", Cycles: 4, OperandBytes: 0},
	0x44: {Mnemonic: "LD B,H", Cycles: 4, OperandBytes: 0},
	0x45: {Mnemonic: "LD B,L", Cycles: 4, OperandBytes: 0},
	0x46: {Mnemonic: "LD B,(HL)", Cycles: 8, OperandBytes: 0},
	0x47: {Mnemonic: "LD B,A", Cycles: 4, OperandBytes: 0},
	0x48: {Mnemonic: "LD C,B", Cycles: 4, OperandBytes: 0},
	0x49: {Mnemonic: "LD C,C", Cycles: 4, OperandBytes: 0},
	0x4A: {Mnemonic: "LD C,D", Cycles: 4, OperandBytes: 0},
	0x4B: {Mnemonic: "LD C,E", Cycles: 4, OperandBytes: 0},
	0x4C: {Mnemonic: "LD C,H", Cycles: 4, OperandBytes: 0},
	0x4D: {Mnemonic: "LD C,L", Cycles: 4, OperandBytes: 0},
	0x4E: {Mnemonic: "LD C,(HL)", Cycles: 8, OperandBytes: 0},
	0x4F: {Mnemonic: "LD C,A", Cycles: 4, OperandBytes: 0},
	// 0x50-0x5F
	0x50: {Mnemonic: "LD D,B", Cycles: 4, OperandBytes: 0},
	0x51: {Mnemonic: "LD D,C", Cycles: 4, OperandBytes: 0},
	0x52: {Mnemonic: "LD D,D", Cycles: 4, OperandBytes: 0},
	0x53: {Mnemonic: "LD D,E", Cycles: 4, OperandBytes: 0},
	0x54: {Mnemonic: "LD D,H", Cycles: 4, OperandBytes: 0},
	0x55: {Mnemonic: "LD D,L", Cycles: 4, OperandBytes: 0},
	0x56: {Mnemonic: "LD D,(HL)", Cycles: 8, OperandBytes: 0},
	0x57: {Mnemonic: "LD D,A", Cycles: 4, OperandBytes: 0},
	0x58: {Mnemonic: "LD E,B", Cycles: 4, OperandBytes: 0},
	0x59: {Mnemonic: "LD E,C", Cycles: 4, OperandBytes: 0},
	0x5A: {Mnemonic: "LD E,D", Cycles: 4, OperandBytes: 0},
	0x5B: {Mnemonic: "LD E,E", Cycles: 4, OperandBytes: 0},
	0x5C: {Mnemonic: "LD E,H", Cycles: 4, OperandBytes: 0},
	0x5D: {Mnemonic: "LD E,L", Cycles: 4, OperandBytes: 0},
	0x5E: {Mnemonic: "LD E,(HL)", Cycles: 8, OperandBytes: 0},
	0x5F: {Mnemonic: "LD E,A", Cycles: 4, OperandBytes: 0},
	// 0x60-0x6F
	0x60: {Mnemonic: "LD H,B", Cycles: 4, OperandBytes: 0},
	0x61: {Mnemonic: "LD H,C", Cycles: 4, OperandBytes: 0},
	0x62: {Mnemonic: "LD H,D", Cycles: 4, OperandBytes: 0},
	0x63: {Mnemonic: "LD H,E", Cycles: 4, OperandBytes: 0},
	0x64: {Mnemonic: "LD H,H", Cycles: 4, OperandBytes: 0},
	0x65: {Mnemonic: "LD H,L", Cycles: 4, OperandBytes: 0},
	0x66: {Mnemonic: "LD H,(HL)", Cycles: 8, OperandBytes: 0},
	0x67: {Mnemonic: "LD H,A", Cycles: 4, OperandBytes: 0},
	0x68: {Mnemonic: "LD L,B", Cycles: 4, OperandBytes: 0},
	0x69: {Mnemonic: "LD L,C", Cycles: 4, OperandBytes: 0},
	0x6A: {Mnemonic: "LD L,D", Cycles: 4, OperandBytes: 0},
	0x6B: {Mnemonic: "LD L,E", Cycles: 4, OperandBytes: 0},
	0x6C: {Mnemonic: "LD L,H", Cycles: 4, OperandBytes: 0},
	0x6D: {Mnemonic: "LD L,L", Cycles: 4, OperandBytes: 0},
	0x6E: {Mnemonic: "LD L,(HL)", Cycles: 8, OperandBytes: 0},
	0x6F: {Mnemonic: "LD L,A", Cycles: 4, OperandBytes: 0},
	// 0x70-0x7F
	0x70: {Mnemonic: "LD (HL),B", Cycles: 8, OperandBytes: 0},
	0x71: {Mnemonic: "LD (HL),C", Cycles: 8, OperandBytes: 0},
	0x72: {Mnemonic: "LD (HL),D", Cycles: 8, OperandBytes: 0},
	0x73: {Mnemonic: "LD (HL),E", Cycles: 8, OperandBytes: 0},
	0x74: {Mnemonic: "LD (HL),H", Cycles: 8, OperandBytes: 0},
	0x75: {Mnemonic: "LD (HL),L", Cycles: 8, OperandBytes: 0},
	0x76: {Mnemonic: "HALT", Cycles: 4, OperandBytes: 0},
	0x77: {Mnemonic: "LD (HL),A", Cycles: 8, OperandBytes: 0},
	0x78: {Mnemonic: "LD A,B", Cycles: 4, OperandBytes: 0},
	0x79: {Mnemonic: "LD A,C", Cycles: 4, OperandBytes: 0},
	0x7A: {Mnemonic: "LD A,D", Cycles: 4, OperandBytes: 0},
	0x7B: {Mnemonic: "LD A,E", Cycles: 4, OperandBytes: 0},
	0x7C: {Mnemonic: "LD A,H", Cycles: 4, OperandBytes: 0},
	0x7D: {Mnemonic: "LD A,L", Cycles: 4, OperandBytes: 0},
	0x7E: {Mnemonic: "LD A,(HL)", Cycles: 8, OperandBytes: 0},
	0x7F: {Mnemonic: "LD A,A", Cycles: 4, OperandBytes: 0},
	// 0x80-0x8F
	0x80: {Mnemonic: "ADD A,B", Cycles: 4, OperandBytes: 0},
	0x81: {Mnemonic: "ADD A,C", Cycles: 4, OperandBytes: 0},
	0x82: {Mnemonic: "ADD A,D", Cycles: 4, OperandBytes: 0},
	0x83: {Mnemonic: "ADD A,E", Cycles: 4, OperandBytes: 0},
	0x84: {Mnemonic: "ADD A,H", Cycles: 4, OperandBytes: 0},
	0x85: {Mnemonic: "ADD A,L", Cycles: 4, OperandBytes: 0},
	0x86: {Mnemonic: "ADD A,(HL)", Cycles: 8, OperandBytes: 0},
	0x87: {Mnemonic: "ADD A,A", Cycles: 4, OperandBytes: 0},
	0x88: {Mnemonic: "ADC A,B", Cycles: 4, OperandBytes: 0},
	0x89: {Mnemonic: "ADC A,C", Cycles: 4, OperandBytes: 0},
	0x8A: {Mnemonic: "ADC A,D", Cycles: 4, OperandBytes: 0},
	0x8B: {Mnemonic: "ADC A,E", Cycles: 4, OperandBytes: 0},
	0x8C: {Mnemonic: "ADC A,H", Cycles: 4, OperandBytes: 0},
	0x8D: {Mnemonic: "ADC A,L", Cycles: 4, OperandBytes: 0},
	0x8E: {Mnemonic: "ADC A,(HL)", Cycles: 8, OperandBytes: 0},
	0x8F: {Mnemonic: "ADC A,A", Cycles: 4, OperandBytes: 0},
	// 0x90-0x9F
	0x90: {Mnemonic: "SUB B", Cycles: 4, OperandBytes: 0},
	0x91: {Mnemonic: "SUB C", Cycles: 4, OperandBytes: 0},
	0x92: {Mnemonic: "SUB D", Cycles: 4, OperandBytes: 0},
	0x93: {Mnemonic: "SUB E", Cycles: 4, OperandBytes: 0},
	0x94: {Mnemonic: "SUB H", Cycles: 4, OperandBytes: 0},
	0x95: {Mnemonic: "SUB L", Cycles: 4, OperandBytes: 0},
	0x96: {Mnemonic: "SUB (HL)", Cycles: 8, OperandBytes: 0},
	0x97: {Mnemonic: "SUB A", Cycles: 4, OperandBytes: 0},
	0x98: {Mnemonic: "SBC A,B", Cycles: 4, OperandBytes: 0},
	0x99: {Mnemonic: "SBC A,C", Cycles: 4, OperandBytes: 0},
	0x9A: {Mnemonic: "SBC A,D", Cycles: 4, OperandBytes: 0},
	0x9B: {Mnemonic: "SBC A,E", Cycles: 4, OperandBytes: 0},
	0x9C: {Mnemonic: "SBC A,H", Cycles: 4, OperandBytes: 0},
	0x9D: {Mnemonic: "SBC A,L", Cycles: 4, OperandBytes: 0},
	0x9E: {Mnemonic: "SBC A,(HL)", Cycles: 8, OperandBytes: 0},
	0x9F: {Mnemonic: "SBC A,A", Cycles: 4, OperandBytes: 0},
	// 0xA0-0xAF
	0xA0: {Mnemonic: "AND B", Cycles: 4, OperandBytes: 0},
	0xA1: {Mnemonic: "AND C", Cycles: 4, OperandBytes: 0},
	0xA2: {Mnemonic: "AND D", Cycles: 4, OperandBytes: 0},
	0xA3: {Mnemonic: "AND E", Cycles: 4, OperandBytes: 0},
	0xA4: {Mnemonic: "AND H", Cycles: 4, OperandBytes: 0},
	0xA5: {Mnemonic: "AND L", Cycles: 4, OperandBytes: 0},
	0xA6: {Mnemonic: "AND (HL)", Cycles: 8, OperandBytes: 0},
	0xA7: {Mnemonic: "AND A", Cycles: 4, OperandBytes: 0},
	0xA8: {Mnemonic: "XOR B", Cycles: 4, OperandBytes: 0},
	0xA9: {Mnemonic: "XOR C", Cycles: 4, OperandBytes: 0},
	0xAA: {Mnemonic: "XOR D", Cycles: 4, OperandBytes: 0},
	0xAB: {Mnemonic: "XOR E", Cycles: 4, OperandBytes: 0},
	0xAC: {Mnemonic: "XOR H", Cycles: 4, OperandBytes: 0},
	0xAD: {Mnemonic: "XOR L", Cycles: 4, OperandBytes: 0},
	0xAE: {Mnemonic: "XOR (HL)", Cycles: 8, OperandBytes: 0},
	0xAF: {Mnemonic: "XOR A", Cycles: 4, OperandBytes: 0},
	// 0xB0-0xBF
	0xB0: {Mnemonic: "OR B", Cycles: 4, OperandBytes: 0},
	0xB1: {Mnemonic: "OR C", Cycles: 4, OperandBytes: 0},
	0xB2: {Mnemonic: "OR D", Cycles: 4, OperandBytes: 0},
	0xB3: {Mnemonic: "OR E", Cycles: 4, OperandBytes: 0},
	0xB4: {Mnemonic: "OR H", Cycles: 4, OperandBytes: 0},
	0xB5: {Mnemonic: "OR L", Cycles: 4, OperandBytes: 0},
	0xB6: {Mnemonic: "OR (HL)", Cycles: 8, OperandBytes: 0},
	0xB7: {Mnemonic: "OR A", Cycles: 4, OperandBytes: 0},
	0xB8: {Mnemonic: "CP B", Cycles: 4, OperandBytes: 0},
	0xB9: {Mnemonic: "CP C", Cycles: 4, OperandBytes: 0},
	0xBA: {Mnemonic: "CP D", Cycles: 4, OperandBytes: 0},
	0xBB: {Mnemonic: "CP E", Cycles: 4, OperandBytes: 0},
	0xBC: {Mnemonic: "CP H", Cycles: 4, OperandBytes: 0},
	0xBD: {Mnemonic: "CP L", Cycles: 4, OperandBytes: 0},
	0xBE: {Mnemonic: "CP (HL)", Cycles: 8, OperandBytes: 0},
	0xBF: {Mnemonic: "CP A", Cycles: 4, OperandBytes: 0},
	// 0xC0-0xCF
	0xC0: {Mnemonic: "RET NZ", Cycles: 20, OperandBytes: 0},
	0xC1: {Mnemonic: "POP BC", Cycles: 12, OperandBytes: 0},
	0xC2: {Mnemonic: "JP NZ,a16", Cycles: 16, OperandBytes: 2},
	0xC3: {Mnemonic: "JP a16", Cycles: 16, OperandBytes: 2},
	0xC4: {Mnemonic: "CALL NZ,a16", Cycles: 24, OperandBytes: 2},
	0xC5: {Mnemonic: "PUSH BC", Cycles: 16, OperandBytes: 0},
	0xC6: {Mnemonic: "ADD A,d8", Cycles: 8, OperandBytes: 1},
	0xC7: {Mnemonic: "RST 00H", Cycles: 16, OperandBytes: 0},
	0xC8: {Mnemonic: "RET Z", Cycles: 20, OperandBytes: 0},
	0xC9: {Mnemonic: "RET", Cycles: 16, OperandBytes: 0},
	0xCA: {Mnemonic: "JP Z,a16", Cycles: 16, OperandBytes: 2},
	0xCB: {Mnemonic: "PREFIX CB", Cycles: 4, OperandBytes: 0},
	0xCC: {Mnemonic: "CALL Z,a16", Cycles: 24, OperandBytes: 2},
	0xCD: {Mnemonic: "CALL a16", Cycles: 24, OperandBytes: 2},
	0xCE: {Mnemonic: "ADC A,d8", Cycles: 8, OperandBytes: 1},
	0xCF: {Mnemonic: "RST 08H", Cycles: 16, OperandBytes: 0},
	// 0xD0-0xDF
	0xD0: {Mnemonic: "RET NC", Cycles: 20, OperandBytes: 0},
	0xD1: {Mnemonic: "POP DE", Cycles: 12, OperandBytes: 0},
	0xD2: {Mnemonic: "JP NC,a16", Cycles: 16, OperandBytes: 2},
	0xD3: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xD4: {Mnemonic: "CALL NC,a16", Cycles: 24, OperandBytes: 2},
	0xD5: {Mnemonic: "PUSH DE", Cycles: 16, OperandBytes: 0},
	0xD6: {Mnemonic: "SUB d8", Cycles: 8, OperandBytes: 1},
	0xD7: {Mnemonic: "RST 10H", Cycles: 16, OperandBytes: 0},
	0xD8: {Mnemonic: "RET C", Cycles: 20, OperandBytes: 0},
	0xD9: {Mnemonic: "RETI", Cycles: 16, OperandBytes: 0},
	0xDA: {Mnemonic: "JP C,a16", Cycles: 16, OperandBytes: 2},
	0xDB: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xDC: {Mnemonic: "CALL C,a16", Cycles: 24, OperandBytes: 2},
	0xDD: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xDE: {Mnemonic: "SBC A,d8", Cycles: 8, OperandBytes: 1},
	0xDF: {Mnemonic: "RST 18H", Cycles: 16, OperandBytes: 0},
	// 0xE0-0xEF
	0xE0: {Mnemonic: "LDH (a8),A", Cycles: 12, OperandBytes: 1},
	0xE1: {Mnemonic: "POP HL", Cycles: 12, OperandBytes: 0},
	0xE2: {Mnemonic: "LDH (C),A", Cycles: 8, OperandBytes: 0},
	0xE3: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xE4: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xE5: {Mnemonic: "PUSH HL", Cycles: 16, OperandBytes: 0},
	0xE6: {Mnemonic: "AND d8", Cycles: 8, OperandBytes: 1},
	0xE7: {Mnemonic: "RST 20H", Cycles: 16, OperandBytes: 0},
	0xE8: {Mnemonic: "ADD SP,r8", Cycles: 16, OperandBytes: 1},
	0xE9: {Mnemonic: "JP (HL)", Cycles: 4, OperandBytes: 0},
	0xEA: {Mnemonic: "LD (a16),A", Cycles: 16, OperandBytes: 2},
	0xEB: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xEC: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xED: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xEE: {Mnemonic: "XOR d8", Cycles: 8, OperandBytes: 1},
	0xEF: {Mnemonic: "RST 28H", Cycles: 16, OperandBytes: 0},
	// 0xF0-0xFF
	0xF0: {Mnemonic: "LDH A,(a8)", Cycles: 12, OperandBytes: 1},
	0xF1: {Mnemonic: "POP AF", Cycles: 12, OperandBytes: 0},
	0xF2: {Mnemonic: "LDH A,(C)", Cycles: 8, OperandBytes: 0},
	0xF3: {Mnemonic: "DI", Cycles: 4, OperandBytes: 0},
	0xF4: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xF5: {Mnemonic: "PUSH AF", Cycles: 16, OperandBytes: 0},
	0xF6: {Mnemonic: "OR d8", Cycles: 8, OperandBytes: 1},
	0xF7: {Mnemonic: "RST 30H", Cycles: 16, OperandBytes: 0},
	0xF8: {Mnemonic: "LD HL,SP+r8", Cycles: 12, OperandBytes: 1},
	0xF9: {Mnemonic: "LD SP,HL", Cycles: 8, OperandBytes: 0},
	0xFA: {Mnemonic: "LD A,(a16)", Cycles: 16, OperandBytes: 2},
	0xFB: {Mnemonic: "EI", Cycles: 4, OperandBytes: 0},
	0xFC: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xFD: {Mnemonic: "undefined", Cycles: 4, OperandBytes: 0},
	0xFE: {Mnemonic: "CP d8", Cycles: 8, OperandBytes: 1},
	0xFF: {Mnemonic: "RST 38H", Cycles: 16, OperandBytes: 0},
}
